# Generated by Django 3.0.6 on 2020-05-17 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Class Name')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='class_student', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=40)),
                ('student_name', models.CharField(max_length=80)),
                ('hidden', models.BooleanField(default=True)),
                ('pdf', models.CharField(max_length=300)),
                ('student_pic', models.ImageField(upload_to='student_pic/')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Classes')),
            ],
        ),
    ]
