# Generated by Django 3.0.6 on 2020-05-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='student_name',
            field=models.CharField(default='test', max_length=80),
            preserve_default=False,
        ),
    ]
