# Generated by Django 3.0.6 on 2020-05-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_post_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pdf',
            field=models.CharField(max_length=300),
        ),
    ]
