# Generated by Django 3.0.6 on 2020-05-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20200516_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='student_pic',
            field=models.ImageField(default='test', upload_to='student_pic/'),
            preserve_default=False,
        ),
    ]
