# Generated by Django 3.0.6 on 2020-05-15 16:35

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('name', models.CharField(choices=[('a', 'Medicine/Health'), ('b', 'Biology'), ('c', 'Chemistry'), ('d', 'Physics'), ('e', 'Astronomy'), ('f', 'Engineering'), ('g', 'English/Writing'), ('h', 'Finance/Business/Consultancy'), ('i', 'Administration/Management'), ('j', 'Arts/Media'), ('k', 'Academia/Education'), ('1', 'Making money'), ('2', 'Helping other people'), ('3', 'Having job security'), ('4', 'Working with people'), ('5', 'Having lots of family time'), ('6', 'Having an exciting job'), ('7', 'Making use of my talents/abilities')], max_length=1, primary_key=True, serialize=False, unique=True, verbose_name='Name')),
                ('o_1', models.IntegerField(default=0, verbose_name='Frequency O1')),
                ('o_2', models.IntegerField(default=0, verbose_name='Frequency O2')),
                ('o_3', models.IntegerField(default=0, verbose_name='Frequency O3')),
                ('o_4', models.IntegerField(default=0, verbose_name='Frequency O4')),
                ('o_5', models.IntegerField(default=0, verbose_name='Frequency O5')),
                ('o_6', models.IntegerField(default=0, verbose_name='Frequency O6')),
                ('o_7', models.IntegerField(default=0, verbose_name='Frequency O7')),
                ('o_a', models.IntegerField(default=0, verbose_name='Frequency Oa')),
                ('o_b', models.IntegerField(default=0, verbose_name='Frequency Ob')),
                ('o_c', models.IntegerField(default=0, verbose_name='Frequency Oc')),
                ('o_d', models.IntegerField(default=0, verbose_name='Frequency Od')),
                ('o_e', models.IntegerField(default=0, verbose_name='Frequency Oe')),
                ('o_f', models.IntegerField(default=0, verbose_name='Frequency Of')),
                ('o_g', models.IntegerField(default=0, verbose_name='Frequency Og')),
                ('o_h', models.IntegerField(default=0, verbose_name='Frequency Oh')),
                ('o_i', models.IntegerField(default=0, verbose_name='Frequency Oi')),
                ('o_j', models.IntegerField(default=0, verbose_name='Frequency Oj')),
                ('o_k', models.IntegerField(default=0, verbose_name='Frequency Ok')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('job', models.CharField(max_length=100, verbose_name='Job Title')),
                ('description', models.CharField(max_length=10000, verbose_name='Description')),
                ('link', models.CharField(max_length=200, verbose_name='Link')),
                ('image', models.ImageField(upload_to='profile_photos/')),
                ('q1_answer', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Making money'), (2, 'Helping other people'), (3, 'Having job security'), (4, 'Working with people'), (5, 'Having lots of family time'), (6, 'Having an exciting job'), (7, 'Making use of my talents/abilities')], max_length=13)),
                ('q2_answer', multiselectfield.db.fields.MultiSelectField(choices=[('a', 'Medicine/Health'), ('b', 'Biology'), ('c', 'Chemistry'), ('d', 'Physics'), ('e', 'Astronomy'), ('f', 'Engineering'), ('g', 'English/Writing'), ('h', 'Finance/Business/Consultancy'), ('i', 'Administration/Management'), ('j', 'Arts/Media'), ('k', 'Academia/Education')], max_length=21)),
            ],
        ),
    ]
