# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-02 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name=b'Name')),
                ('job', models.CharField(max_length=100, verbose_name=b'Job Title')),
                ('description', models.CharField(max_length=10000, verbose_name=b'Description')),
                ('link', models.CharField(max_length=200, verbose_name=b'Link')),
                ('image', models.ImageField(upload_to=b'profile_photos/')),
                ('q1_answer', multiselectfield.db.fields.MultiSelectField(choices=[(1, b'Making money'), (2, b'Helping other people'), (3, b'Having job security'), (4, b'Working with people'), (5, b'Having lots of family time'), (6, b'Having an exciting job'), (7, b'Making use of my talents/abilities')], max_length=13)),
                ('q2_answer', multiselectfield.db.fields.MultiSelectField(choices=[(1, b'Medicine/Health'), (2, b'Biology'), (3, b'Chemistry'), (4, b'Physics'), (5, b'Astronomy'), (6, b'Engineering'), (7, b'English/Writing'), (8, b'Finance/Business/Consultancy'), (9, b'Administration/Management'), (10, b'Arts/Media'), (11, b'Academia/Education')], max_length=23)),
            ],
        ),
    ]
