# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-09 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200409_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='o_1',
            field=models.IntegerField(default=0, verbose_name=b'Frequency O1'),
        ),
        migrations.AlterField(
            model_name='option',
            name='o_2',
            field=models.IntegerField(default=0, verbose_name=b'Frequency O2'),
        ),
        migrations.AlterField(
            model_name='option',
            name='o_3',
            field=models.IntegerField(default=0, verbose_name=b'Frequency O3'),
        ),
        migrations.AlterField(
            model_name='option',
            name='o_4',
            field=models.IntegerField(default=0, verbose_name=b'Frequency O4'),
        ),
        migrations.AlterField(
            model_name='option',
            name='o_5',
            field=models.IntegerField(default=0, verbose_name=b'Frequency O5'),
        ),
        migrations.AlterField(
            model_name='option',
            name='o_6',
            field=models.IntegerField(default=0, verbose_name=b'Frequency O6'),
        ),
        migrations.AlterField(
            model_name='option',
            name='o_7',
            field=models.IntegerField(default=0, verbose_name=b'Frequency O7'),
        ),
        migrations.AlterField(
            model_name='option',
            name='o_a',
            field=models.IntegerField(default=0, verbose_name=b'Frequency Oa'),
        ),
        migrations.AlterField(
            model_name='option',
            name='o_b',
            field=models.IntegerField(default=0, verbose_name=b'Frequency Ob'),
        ),
        migrations.AlterField(
            model_name='option',
            name='o_c',
            field=models.IntegerField(default=0, verbose_name=b'Frequency Oc'),
        ),
        migrations.AlterField(
            model_name='option',
            name='o_d',
            field=models.IntegerField(default=0, verbose_name=b'Frequency Od'),
        ),
        migrations.AlterField(
            model_name='option',
            name='o_e',
            field=models.IntegerField(default=0, verbose_name=b'Frequency Oe'),
        ),
        migrations.AlterField(
            model_name='option',
            name='o_f',
            field=models.IntegerField(default=0, verbose_name=b'Frequency Of'),
        ),
        migrations.AlterField(
            model_name='option',
            name='o_g',
            field=models.IntegerField(default=0, verbose_name=b'Frequency Og'),
        ),
        migrations.AlterField(
            model_name='option',
            name='o_h',
            field=models.IntegerField(default=0, verbose_name=b'Frequency Oh'),
        ),
        migrations.AlterField(
            model_name='option',
            name='o_i',
            field=models.IntegerField(default=0, verbose_name=b'Frequency Oi'),
        ),
        migrations.AlterField(
            model_name='option',
            name='o_j',
            field=models.IntegerField(default=0, verbose_name=b'Frequency Oj'),
        ),
        migrations.AlterField(
            model_name='option',
            name='o_k',
            field=models.IntegerField(default=0, verbose_name=b'Frequency Ok'),
        ),
    ]
